# Generated by Django 5.0.3 on 2024-04-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(default='default_category.png', upload_to='category')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('liter', models.FloatField()),
                ('description', models.CharField(max_length=400)),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
                ('tax_code', models.IntegerField(blank=True, null=True)),
                ('warehouse', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_stock', models.BooleanField(default=True)),
                ('branches', models.ManyToManyField(related_name='branch_product', to='admins.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('image', models.ManyToManyField(related_name='product_image', to='product.productimage')),
            ],
        ),
    ]
